"""Adjust Review model for case where game does not exist in IGDB api

Revision ID: 7293431a5cc9
Revises: 46f56245a157
Create Date: 2024-02-15 22:55:05.040015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7293431a5cc9'
down_revision = '46f56245a157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('igdb_game_id', sa.String(), nullable=True))
        batch_op.alter_column('game_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('igdb_game_id')

    # ### end Alembic commands ###
