"""Made Favorite association table into a Model. Added relationships

Revision ID: 97ee6d5c2055
Revises: 0b08077c2931
Create Date: 2024-03-16 20:20:50.373232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ee6d5c2055'
down_revision = '0b08077c2931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('igdb_game_id', sa.String(), nullable=True))
        batch_op.alter_column('game_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('igdb_game_id')

    # ### end Alembic commands ###
